runtime: go116
service: cv

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6
  min_instances: 0
  max_instances: 2
  max_concurrent_requests: 70